% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Feb-2025 22:05:07
%  MATLAB version: 25.1.0.2852912 (R2025a) Prerelease Update 3
% -------------------------------------------------------------------
saveVarsMat = load('Data2.mat');

Part1Data = saveVarsMat.Part1Data; % <1x1 table> unsupported class

clear saveVarsMat;
